// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: risk_engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskEngine_CalculateBetaScenario_FullMethodName = "/riskengine.RiskEngine/CalculateBetaScenario"
)

// RiskEngineClient is the client API for RiskEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskEngineClient interface {
	CalculateBetaScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error)
}

type riskEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskEngineClient(cc grpc.ClientConnInterface) RiskEngineClient {
	return &riskEngineClient{cc}
}

func (c *riskEngineClient) CalculateBetaScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (*ScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioResponse)
	err := c.cc.Invoke(ctx, RiskEngine_CalculateBetaScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskEngineServer is the server API for RiskEngine service.
// All implementations must embed UnimplementedRiskEngineServer
// for forward compatibility.
type RiskEngineServer interface {
	CalculateBetaScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error)
	mustEmbedUnimplementedRiskEngineServer()
}

// UnimplementedRiskEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskEngineServer struct{}

func (UnimplementedRiskEngineServer) CalculateBetaScenario(context.Context, *ScenarioRequest) (*ScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBetaScenario not implemented")
}
func (UnimplementedRiskEngineServer) mustEmbedUnimplementedRiskEngineServer() {}
func (UnimplementedRiskEngineServer) testEmbeddedByValue()                    {}

// UnsafeRiskEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskEngineServer will
// result in compilation errors.
type UnsafeRiskEngineServer interface {
	mustEmbedUnimplementedRiskEngineServer()
}

func RegisterRiskEngineServer(s grpc.ServiceRegistrar, srv RiskEngineServer) {
	// If the following call panics, it indicates UnimplementedRiskEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskEngine_ServiceDesc, srv)
}

func _RiskEngine_CalculateBetaScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskEngineServer).CalculateBetaScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskEngine_CalculateBetaScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskEngineServer).CalculateBetaScenario(ctx, req.(*ScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskEngine_ServiceDesc is the grpc.ServiceDesc for RiskEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riskengine.RiskEngine",
	HandlerType: (*RiskEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateBetaScenario",
			Handler:    _RiskEngine_CalculateBetaScenario_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk_engine.proto",
}
