// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: risk_engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionLeg_Type int32

const (
	OptionLeg_CALL OptionLeg_Type = 0
	OptionLeg_PUT  OptionLeg_Type = 1
)

// Enum value maps for OptionLeg_Type.
var (
	OptionLeg_Type_name = map[int32]string{
		0: "CALL",
		1: "PUT",
	}
	OptionLeg_Type_value = map[string]int32{
		"CALL": 0,
		"PUT":  1,
	}
)

func (x OptionLeg_Type) Enum() *OptionLeg_Type {
	p := new(OptionLeg_Type)
	*p = x
	return p
}

func (x OptionLeg_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionLeg_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_risk_engine_proto_enumTypes[0].Descriptor()
}

func (OptionLeg_Type) Type() protoreflect.EnumType {
	return &file_risk_engine_proto_enumTypes[0]
}

func (x OptionLeg_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionLeg_Type.Descriptor instead.
func (OptionLeg_Type) EnumDescriptor() ([]byte, []int) {
	return file_risk_engine_proto_rawDescGZIP(), []int{0, 0}
}

type OptionLeg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OptionLeg_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=riskengine.OptionLeg_Type" json:"type,omitempty"`
	Strike        float64                `protobuf:"fixed64,2,opt,name=strike,proto3" json:"strike,omitempty"`
	Expiry        string                 `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"` // YYYY-MM-DD
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionLeg) Reset() {
	*x = OptionLeg{}
	mi := &file_risk_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionLeg) ProtoMessage() {}

func (x *OptionLeg) ProtoReflect() protoreflect.Message {
	mi := &file_risk_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionLeg.ProtoReflect.Descriptor instead.
func (*OptionLeg) Descriptor() ([]byte, []int) {
	return file_risk_engine_proto_rawDescGZIP(), []int{0}
}

func (x *OptionLeg) GetType() OptionLeg_Type {
	if x != nil {
		return x.Type
	}
	return OptionLeg_CALL
}

func (x *OptionLeg) GetStrike() float64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

func (x *OptionLeg) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *OptionLeg) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ScenarioRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpotPrice         float64                `protobuf:"fixed64,1,opt,name=spot_price,json=spotPrice,proto3" json:"spot_price,omitempty"`
	RiskFreeRate      float64                `protobuf:"fixed64,2,opt,name=risk_free_rate,json=riskFreeRate,proto3" json:"risk_free_rate,omitempty"`
	Volatility        float64                `protobuf:"fixed64,3,opt,name=volatility,proto3" json:"volatility,omitempty"`
	ScenarioPctChange float64                `protobuf:"fixed64,4,opt,name=scenario_pct_change,json=scenarioPctChange,proto3" json:"scenario_pct_change,omitempty"`
	Beta              float64                `protobuf:"fixed64,5,opt,name=beta,proto3" json:"beta,omitempty"`
	Legs              []*OptionLeg           `protobuf:"bytes,6,rep,name=legs,proto3" json:"legs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScenarioRequest) Reset() {
	*x = ScenarioRequest{}
	mi := &file_risk_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioRequest) ProtoMessage() {}

func (x *ScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioRequest.ProtoReflect.Descriptor instead.
func (*ScenarioRequest) Descriptor() ([]byte, []int) {
	return file_risk_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioRequest) GetSpotPrice() float64 {
	if x != nil {
		return x.SpotPrice
	}
	return 0
}

func (x *ScenarioRequest) GetRiskFreeRate() float64 {
	if x != nil {
		return x.RiskFreeRate
	}
	return 0
}

func (x *ScenarioRequest) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *ScenarioRequest) GetScenarioPctChange() float64 {
	if x != nil {
		return x.ScenarioPctChange
	}
	return 0
}

func (x *ScenarioRequest) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *ScenarioRequest) GetLegs() []*OptionLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

type ScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioPnl   float64                `protobuf:"fixed64,1,opt,name=scenario_pnl,json=scenarioPnl,proto3" json:"scenario_pnl,omitempty"`
	ScenarioDelta float64                `protobuf:"fixed64,2,opt,name=scenario_delta,json=scenarioDelta,proto3" json:"scenario_delta,omitempty"`
	ScenarioGamma float64                `protobuf:"fixed64,3,opt,name=scenario_gamma,json=scenarioGamma,proto3" json:"scenario_gamma,omitempty"`
	ScenarioTheta float64                `protobuf:"fixed64,4,opt,name=scenario_theta,json=scenarioTheta,proto3" json:"scenario_theta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioResponse) Reset() {
	*x = ScenarioResponse{}
	mi := &file_risk_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioResponse) ProtoMessage() {}

func (x *ScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioResponse.ProtoReflect.Descriptor instead.
func (*ScenarioResponse) Descriptor() ([]byte, []int) {
	return file_risk_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ScenarioResponse) GetScenarioPnl() float64 {
	if x != nil {
		return x.ScenarioPnl
	}
	return 0
}

func (x *ScenarioResponse) GetScenarioDelta() float64 {
	if x != nil {
		return x.ScenarioDelta
	}
	return 0
}

func (x *ScenarioResponse) GetScenarioGamma() float64 {
	if x != nil {
		return x.ScenarioGamma
	}
	return 0
}

func (x *ScenarioResponse) GetScenarioTheta() float64 {
	if x != nil {
		return x.ScenarioTheta
	}
	return 0
}

var File_risk_engine_proto protoreflect.FileDescriptor

const file_risk_engine_proto_rawDesc = "" +
	"\n" +
	"\x11risk_engine.proto\x12\n" +
	"riskengine\"\xa2\x01\n" +
	"\tOptionLeg\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.riskengine.OptionLeg.TypeR\x04type\x12\x16\n" +
	"\x06strike\x18\x02 \x01(\x01R\x06strike\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\tR\x06expiry\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\"\x19\n" +
	"\x04Type\x12\b\n" +
	"\x04CALL\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\"\xe5\x01\n" +
	"\x0fScenarioRequest\x12\x1d\n" +
	"\n" +
	"spot_price\x18\x01 \x01(\x01R\tspotPrice\x12$\n" +
	"\x0erisk_free_rate\x18\x02 \x01(\x01R\friskFreeRate\x12\x1e\n" +
	"\n" +
	"volatility\x18\x03 \x01(\x01R\n" +
	"volatility\x12.\n" +
	"\x13scenario_pct_change\x18\x04 \x01(\x01R\x11scenarioPctChange\x12\x12\n" +
	"\x04beta\x18\x05 \x01(\x01R\x04beta\x12)\n" +
	"\x04legs\x18\x06 \x03(\v2\x15.riskengine.OptionLegR\x04legs\"\xaa\x01\n" +
	"\x10ScenarioResponse\x12!\n" +
	"\fscenario_pnl\x18\x01 \x01(\x01R\vscenarioPnl\x12%\n" +
	"\x0escenario_delta\x18\x02 \x01(\x01R\rscenarioDelta\x12%\n" +
	"\x0escenario_gamma\x18\x03 \x01(\x01R\rscenarioGamma\x12%\n" +
	"\x0escenario_theta\x18\x04 \x01(\x01R\rscenarioTheta2`\n" +
	"\n" +
	"RiskEngine\x12R\n" +
	"\x15CalculateBetaScenario\x12\x1b.riskengine.ScenarioRequest\x1a\x1c.riskengine.ScenarioResponseB\tZ\a./protob\x06proto3"

var (
	file_risk_engine_proto_rawDescOnce sync.Once
	file_risk_engine_proto_rawDescData []byte
)

func file_risk_engine_proto_rawDescGZIP() []byte {
	file_risk_engine_proto_rawDescOnce.Do(func() {
		file_risk_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_risk_engine_proto_rawDesc), len(file_risk_engine_proto_rawDesc)))
	})
	return file_risk_engine_proto_rawDescData
}

var file_risk_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_risk_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_risk_engine_proto_goTypes = []any{
	(OptionLeg_Type)(0),      // 0: riskengine.OptionLeg.Type
	(*OptionLeg)(nil),        // 1: riskengine.OptionLeg
	(*ScenarioRequest)(nil),  // 2: riskengine.ScenarioRequest
	(*ScenarioResponse)(nil), // 3: riskengine.ScenarioResponse
}
var file_risk_engine_proto_depIdxs = []int32{
	0, // 0: riskengine.OptionLeg.type:type_name -> riskengine.OptionLeg.Type
	1, // 1: riskengine.ScenarioRequest.legs:type_name -> riskengine.OptionLeg
	2, // 2: riskengine.RiskEngine.CalculateBetaScenario:input_type -> riskengine.ScenarioRequest
	3, // 3: riskengine.RiskEngine.CalculateBetaScenario:output_type -> riskengine.ScenarioResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_risk_engine_proto_init() }
func file_risk_engine_proto_init() {
	if File_risk_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_risk_engine_proto_rawDesc), len(file_risk_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_engine_proto_goTypes,
		DependencyIndexes: file_risk_engine_proto_depIdxs,
		EnumInfos:         file_risk_engine_proto_enumTypes,
		MessageInfos:      file_risk_engine_proto_msgTypes,
	}.Build()
	File_risk_engine_proto = out.File
	file_risk_engine_proto_goTypes = nil
	file_risk_engine_proto_depIdxs = nil
}
